[_BASE] = LAYOUT_ergodox_pretty(//------|-----------------|---------X---------------|---------------$---------------/**/------------$---------------|---------------X---------------|---------------|---------------|---------------|---------------
    TO(_TEST),        xxxxxxxx,         xxxxxxxx,         KC_CAPSLOCK,   xxxxxxxx,       xxxxxxxx,       xxxxxxxx,       /**/            xxxxxxxx,       xxxxxxxx,       xxxxxxxx,       KC_CAPSLOCK,    xxxxxxxx,       xxxxxxxx,       xxxxxxxx,
    KC_MINUS,         KC_Q,             LT(_SYMB,KC_W), KC_E,           KC_R,           KC_T,           KC__VOLUP,      /**/            KC_MS_WH_UP,    KC_Y,           KC_U,           KC_I,           LT(_SYMB,KC_O), KC_P,             KC_BSLASH,
    KC_ESC,   /***/   CTL_T(KC_A),      SFT_T(KC_S),    ALT_T(KC_D),    CMD_T(KC_F),    KC_G,           /**/            /**/            /**/            KC_H,           CMD_T(KC_J),   ALT_T(KC_K),      SFT_T(KC_L),   CTL_T(KC_SCOLON),KC_UNDS,
    xxxxxxxx,         LT(_MOVE,KC_Z),   LT(_SYMB,KC_X), LT(_FUN,KC_C),  KC_V,           KC_B,           KC__VOLDOWN,    /**/            KC_MS_WH_DOWN,  KC_N,           KC_M,           LT(_FUN,KC_COMMA),LT(_SYMB,KC_DOT), KC_SLASH ,        KC_UNDS,
    xxxxxxxx,         CTL_T(KC_LEFT),   xxxxxxxx,       KC_BSPACE,    KC_SPACE,       /*-------------*/             /**/            /*-------------*/                 KC_ENTER,      KC_TAB,          xxxxxxxx,         CTL_T(KC_RGHT),   xxxxxxxx,
    //--------------|***************|***************|***************|***************|---------------$---------------/**/----------------------------$---------------|***************|***************|***************|***************|---------------
    /*----------------------------------|----------------------------------------*/ KC__MUTE,       xxxxxxxx,       /**/            xxxxxxxx,       xxxxxxxx,
    /*----------------------------------|--------------------------------------------------------*/ xxxxxxxx,       /**/            xxxxxxxx,       /***************/
    /*----------------------------------|------------------------*/ BTL_OUTER,       xxxxxxxx,   xxxxxxxx,       /**/            xxxxxxxx,      xxxxxxxx,    BTR_OUTER),
