[_SYMB] = LAYOUT_ergodox_pretty(//------|--------|---------------X---------------|---------------$------------------/**/------------$---------------|---------------X---------------|---------------|---------------|---------------|---------------
    xxxxxxxx,       KC_F1,          KC_F2,          KC_F3,          KC_F4,          KC_F5,          xxxxxxxx,       /**/            xxxxxxxx,       KC_F6,          KC_F7,          KC_F8,          KC_F9,          KC_F10,         TO(_BASE),
    xxxxxxxx,       KC_EXLM,          KC_AT,          KC_LCBR,        KC_RCBR,        KC_PIPE,        xxxxxxxx,       /**/            xxxxxxxx,       KC_QUOTE,       KC_7,           KC_8,           KC_9,           KC_EQUAL,       xxxxxxxx,
    xxxxxxxx,       KC_HASH,   KC_DLR,         KC_LPRN,        KC_RPRN,        KC_GRAVE,                       /**/            /**/            KC_0,           KC_4,           KC_5,           KC_6,           KC_PLUS,   xxxxxxxx,
    KC_AMPR,        KC_PERC,          KC_CIRC,        KC_LBRACKET,    KC_RBRACKET,    KC_TILD,        xxxxxxxx,       /**/            xxxxxxxx,       KC_ASTR,        KC_1,           KC_2,           KC_3,           KC_MINUS,       xxxxxxxx,
    xxxxxxxx,       xxxxxxxx,       xxxxxxxx,       xxxxxxxx,       KC_LCTL,        /***************/               /**/            /***************/               KC_RCTL,        xxxxxxxx,       xxxxxxxx,         xxxxxxxx,        xxxxxxxx,
    //--------------|***************|***************|***************|***************|---------------$---------------/**/----------------------------$---------------|***************|***************|***************|***************|---------------
    /*----------------------------------|----------------------------------------*/ xxxxxxxx,       xxxxxxxx,       /**/            xxxxxxxx,      xxxxxxxx,
    /*----------------------------------|--------------------------------------------------------*/ xxxxxxxx,       /**/            xxxxxxxx,
    /*----------------------------------|------------------------*/ KC_LCTL,       xxxxxxxx,       xxxxxxxx,       /**/            xxxxxxxx,      xxxxxxxx,        KC_RCTL),
